name: Auth to Terraform
on: [push]
jobs:
  _asdf:
    runs-on: 'ubuntu-latest'

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/{{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@{{ secrets.PROJECT_ID }}.iam.gserviceaccount.com'
        access_token_lifetime: '300s' # optional, default: '3600s' (1 hour)

    - name: ECHO
      run: |-
        echo "${{ steps.auth.outputs.id_token }}"
      env:
        GOOGLE_OAUTH_ACCESS_TOKEN: "${{ steps.auth.outputs.id_token }}"
