name: .NET

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  # init:
  #   runs-on: ubuntu-latest
    # steps:
    #   - name: Set up Cloud SDK
    #     uses: google-github-actions/setup-gcloud@master
    #     with:
    #       project_id: ${{ secrets.GCP_PROJECT_ID }}
    #       service_account_key: ${{ secrets.GCP_SA_KEY }}
    #       export_default_credentials: true
    #   - name: Use gcloud CLI
    #     run: gcloud info

  build:
    runs-on: ubuntu-latest

# Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # add SECRETs @ https://github.com/garrettwong/gcp-csharp-app/settings/secrets/actions
    # PROJECT_NUMBER="268323096258"
    # POOL_ID="github-pool"
    # PROVIDER_ID="github-provider"
    # SERVICE_ACCOUNT="workload-identity-sa@gwc-sandbox.iam.gserviceaccount.com"
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        # create_credentials_file: true
        workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.POOL_ID }}/providers/${{ secrets.PROVIDER_ID }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT }}'
        access_token_lifetime: '300s' # optional, default: '3600s' (1 hour)

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
      env:
        # GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}